### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by Antis0cial** [Storj/storjshare-cli#118]
### Package Versions
```
~$ storjshare --version
StorjShare: 4.0.5
Core:       1.4.0
Protocol:   0.7.1

~$ node --version
v6.2.2
```

### Error
I left running storjshare and went to work, this is what I've found when I came back.

```
{"level":"info","message":"received PING from c22b9d7cbd82924e031197ebf806ae26a0237e9d, sending PONG","timestamp":"2016-07-12T13:26:16.215Z"}
{"level":"info","message":"replying to message to 5c8a48e9884709ef26906b911e6c78ea75f42d17","timestamp":"2016-07-12T13:26:16.215Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.7.1\",\"address\":\"server020.storj.dk\",\"port\":5720,\"nodeID\":\"c22b9d7cbd82924e031197ebf806ae26a0237e9d\",\"lastSeen\":1468329983886}","timestamp":"2016-07-12T13:26:23.886Z"}
{"level":"info","message":"received PING from c22b9d7cbd82924e031197ebf806ae26a0237e9d, sending PONG","timestamp":"2016-07-12T13:26:23.993Z"}
{"level":"info","message":"replying to message to f1f79a842b7cacae323ef03a23a1601fa5463a5f","timestamp":"2016-07-12T13:26:23.993Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.7.1\",\"address\":\"server019.storj.dk\",\"port\":5819,\"nodeID\":\"bf55923a1b662436f3cb20c5ab1a9a2c48cb21e1\",\"lastSeen\":1468329992806}","timestamp":"2016-07-12T13:26:32.806Z"}
{"level":"info","message":"received PING from bf55923a1b662436f3cb20c5ab1a9a2c48cb21e1, sending PONG","timestamp":"2016-07-12T13:26:32.913Z"}
{"level":"info","message":"replying to message to 63167869d12a8ed3baf9dd83e46ceb0cbfbc1fe0","timestamp":"2016-07-12T13:26:32.914Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.7.1\",\"address\":\"server016.storj.dk\",\"port\":5616,\"nodeID\":\"02d7885d60ee045907e51d3a1e5a5f2a7845d2e5\",\"lastSeen\":1468329994661}","timestamp":"2016-07-12T13:26:34.661Z"}
{"level":"info","message":"received PING from 02d7885d60ee045907e51d3a1e5a5f2a7845d2e5, sending PONG","timestamp":"2016-07-12T13:26:34.771Z"}
{"level":"info","message":"replying to message to e2d7d0300a55a268cdea474eb1471f4b5103cd44","timestamp":"2016-07-12T13:26:34.771Z"}
{"level":"warn","message":"tunnel connection lost, reason: socket hang up","timestamp":"2016-07-12T13:26:39.193Z"}
{"level":"info","message":"sending OPEN_TUNNEL message to {\"protocol\":\"0.7.1\",\"address\":\"75.70.181.20\",\"port\":4000,\"nodeID\":\"6750e22dd6f96e111f6c0f89f12170d85764c717\",\"lastSeen\":1468329999195}","timestamp":"2016-07-12T13:26:39.196Z"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by littleskunk** [comment]
Node version 6.2.2 is not supported. Please follow this and try again: https://storj.readme.io/docs/storjshare-troubleshooting-guide#wrong-node-version

I will close the issue. If you get the error again with the correct node version please reopen the issue.
