### ISSUE TITLE
One off "Error: not opened"

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#127]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Storjshare : 5.0.0
Core:          2.0.0
Protocol:    0.7.1
```

Replace the values below using the output from `node --version`.

```
v4.4.6
```

### Expected Behavior

Zero error messages to the console!

### Actual Behavior

fs2 store # /usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/ws/lib/                  WebSocket.js:219
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modu                  les/ws/lib/WebSocket.js:219:16)
    at TunnelMuxer.<anonymous> (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/                  lib/tunnel/server.js:243:14)
    at emitOne (events.js:77:13)
    at TunnelMuxer.emit (events.js:169:7)
    at readableAddChunk (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_mo                  dules/readable-stream/lib/_stream_readable.js:210:18)
    at TunnelMuxer.Readable.push (/usr/lib64/node_modules/storjshare-cli/node_modules/stor                  j/node_modules/readable-stream/lib/_stream_readable.js:169:10)
    at TunnelMuxer.Transform.push (/usr/lib64/node_modules/storjshare-cli/node_modules/sto                  rj/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at afterTransform (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modu                  les/readable-stream/lib/_stream_transform.js:79:51)
    at TransformState.afterTransform (/usr/lib64/node_modules/storjshare-cli/node_modules/                  storj/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at TunnelMuxer._muxDataChannel (/usr/lib64/node_modules/storjshare-cli/node_modules/st                  orj/lib/tunnel/multiplexer.js:61:3)
    at TunnelMuxer._transform (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/l                  ib/tunnel/multiplexer.js:78:19)
    at TunnelMuxer.Transform._read (/usr/lib64/node_modules/storjshare-cli/node_modules/st                  orj/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at TunnelMuxer.Transform._write (/usr/lib64/node_modules/storjshare-cli/node_modules/s                  torj/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/rea                  dable-stream/lib/_stream_writable.js:319:64)

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. (4) node server had been running for a dozen or so hours
2. Randomly appeared on console
3. Gentoo linux with NodeJs and Storjshare installed as root, but run under a separate "storj" non-privileged account.
4.  First time I've seen this error since I started running around July 9th.

**Comment by 1credit** [comment]
This is no longer a one-off issue, with (5) CLI processes running, I'm restarting 2-3 of them every day.  Here is one console output I caught on a process that died after only perhaps running 10 minutes.

fs2 local.d # /usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/ws/lib/WebSocke  t.js:219
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/ws/lib  /WebSocket.js:219:16)
    at TunnelMuxer.<anonymous> (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/lib/tunnel  /server.js:243:14)
    at emitOne (events.js:77:13)
    at TunnelMuxer.emit (events.js:169:7)
    at readableAddChunk (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/read  able-stream/lib/_stream_readable.js:210:18)
    at TunnelMuxer.Readable.push (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_mod  ules/readable-stream/lib/_stream_readable.js:169:10)
    at TunnelMuxer.Transform.push (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_mo  dules/readable-stream/lib/_stream_transform.js:123:32)
    at afterTransform (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/readab  le-stream/lib/_stream_transform.js:79:51)
    at TransformState.afterTransform (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node  _modules/readable-stream/lib/_stream_transform.js:58:12)
    at TunnelMuxer._muxDataChannel (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/lib/tu  nnel/multiplexer.js:61:3)
    at TunnelMuxer._transform (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/lib/tunnel/  multiplexer.js:78:19)
    at TunnelMuxer.Transform._read (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_m  odules/readable-stream/lib/_stream_transform.js:159:10)
    at TunnelMuxer.Transform._write (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_  modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/readable-stre  am/lib/_stream_writable.js:319:64)

I've turned loglevel back up to 3 on my primary server in hopes of catching something useful.

**Comment by 1credit** [comment]
3 processes died this morning while I was busy elsewhere.  Only one set of messages captured (likely due to only one of the nodes having been restarted on the ssh console currently up):

fs2 node2 # /usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/ws/lib/WebSocket.js:219
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/ws/lib/WebSocket.js:219:16)
    at TunnelMuxer.<anonymous> (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/lib/tunnel/server.js:243:14)
    at emitOne (events.js:77:13)
    at TunnelMuxer.emit (events.js:169:7)
    at readableAddChunk (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/readable-stream/lib/_stream_readable.js:210:18)
    at TunnelMuxer.Readable.push (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/readable-stream/lib/_stream_readable.js:169:10)
    at TunnelMuxer.Transform.push (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at afterTransform (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/readable-stream/lib/_stream_transform.js:79:51)
    at TransformState.afterTransform (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at TunnelMuxer._muxDataChannel (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/lib/tunnel/multiplexer.js:61:3)

level 3 log files from all three nodes attached.

Note this appears to be occurring more and more frequently.  I use to lose perhaps one node a day, I've restarted 3 in the past 6 hours, some more than once.
[node2.zip](https://github.com/Storj/storjshare-cli/files/378702/node2.zip)

**Comment by 1credit** [comment]
Received these errors within seconds of restarting 3 nodes (via a startup script, so don't know which one generated it).  I was surprised to see all 4 nodes are still up and running and eating CPU.

 events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::4020
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at Transport.HTTPTransport._open (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/lib/transports/http.js:84:16)
    at Transport._open (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/lib/network/transport.js:70:48)
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/lib/rpc.js:107:10
    at Transport.RPC._trigger (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/lib/rpc.js:293:12)
    at Transport.RPC.open (/usr/lib64/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/lib/rpc.js:106:8)

**Comment by bookchin** [comment]
That last error indicates that the process is already running and those ports are in use. I have a fix for the original issue staged, just finishing unit tests now.

**Comment by 1credit** [comment]
But there in is the rub... the ports are dedicated to each node by range.  Only thing I can think of is that they are not being released when the node process dies.

**Comment by bookchin** [comment]
Are you running with PM2 now?

**Comment by 1credit** [comment]
No.  I've been manually restarting the processes when my monitoring "top" doesn't show all 4 of them.  A quick "ps ax | grep node" tells me which are done.   Alas, at the farm now and until mid-day Tuesday, so it will not be quiet as convenient to watch and restart things.
