### ISSUE TITLE
Crash with Error: invalid compressed data

### ISSUE THREAD

**Issue by Puychack** [Storj/storjshare-cli#137]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 5.0.1
Core:       2.0.7
Protocol:   0.7.1
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

Shoud not crash

### Actual Behavior

Storjshare crashed with error meesage : 

```
storj-1 (err): Error: invalid compressed data
storj-1 (err):     at Receiver.error (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/ws/lib/Receiver.js:321:18)
storj-1 (err):     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/ws/lib/Receiver.js:609:25
storj-1 (err):     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/ws/lib/Receiver.js:365:9
storj-1 (err):     at InflateRaw.onError (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/ws/lib/PerMessageDeflate.js:254:5)
storj-1 (err):     at emitOne (events.js:77:13)
storj-1 (err):     at InflateRaw.emit (events.js:169:7)
storj-1 (err):     at Zlib._handle.onerror (zlib.js:366:10)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. crash happened 18 hours after upgrade to cli 5.0.1

**Comment by Puychack** [comment]
Happened first time after upgrade to core 2.0.3. I didn't experienced a single crash since core 1.3.1

**Comment by RDash21** [comment]
Same here,

```
$ storjshare --version
StorjShare: 5.0.1
Core:       2.0.7
Protocol:   0.7.1
```

```
storjshare-0 (err): Error: write after end
storjshare-0 (err):     at writeAfterEnd (/usr/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/readable-stream/lib/_stream_writable.js:201:12)
storjshare-0 (err):     at PassThrough.Writable.write (/usr/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/readable-stream/lib/_stream_writable.js:244:20)
storjshare-0 (err):     at WebSocket.<anonymous> (/usr/lib/node_modules/storjshare-cli/node_modules/storj/lib/datachannel/server.js:173:17)
storjshare-0 (err):     at emitTwo (events.js:87:13)
storjshare-0 (err):     at WebSocket.emit (events.js:172:7)
storjshare-0 (err):     at Receiver.ontext (/usr/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/ws/lib/WebSocket.js:841:10)
storjshare-0 (err):     at /usr/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/ws/lib/Receiver.js:536:18
storjshare-0 (err):     at Receiver.applyExtensions (/usr/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/ws/lib/Receiver.js:371:5)
storjshare-0 (err):     at /usr/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/ws/lib/Receiver.js:508:14
```

Still it keeps on accepting contracts.

More information:
```
OS: Debian Jessie X86_64
```
