### ISSUE TITLE
Error: Point does not lie on the curve

### ISSUE THREAD

**Issue by jackwk** [Storj/storjshare-cli#140]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 5.0.1
Core:       2.0.6
Protocol:   0.7.1
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

Storjshare-cli running fine while scheduled in pm2. 

### Actual Behavior

Randomly started looking at the logs and got this error. After about a minute storjshare started running fine. 

```
storjshare-0 (err): [Error: Point does not lie on the curve]
storjshare-0 (err): Error: Unable to find valid recovery factor
storjshare-0 (err):     at ECDSA.calci (/home/osmc/.nvm/versions/node/v4.4.4/lib                                      /node_modules/storjshare-cli/node_modules/storj/node_modules/bitcore-lib/lib/cry                                      pto/ecdsa.js:56:9)
storjshare-0 (err):     at Message._sign (/home/osmc/.nvm/versions/node/v4.4.4/l                                      ib/node_modules/storjshare-cli/node_modules/storj/node_modules/bitcore-message/l                                      ib/message.js:51:9)
storjshare-0 (err):     at Message.sign (/home/osmc/.nvm/versions/node/v4.4.4/li                                      b/node_modules/storjshare-cli/node_modules/storj/node_modules/bitcore-message/li                                      b/message.js:62:24)
storjshare-0 (err):     at KeyPair.sign (/home/osmc/.nvm/versions/node/v4.4.4/li                                      b/node_modules/storjshare-cli/node_modules/storj/lib/keypair.js:77:29)
storjshare-0 (err):     at FarmerInterface.Network._signMessage (/home/osmc/.nvm                                      /versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/lib/net                                      work/index.js:362:33)
storjshare-0 (err):     at /home/osmc/.nvm/versions/node/v4.4.4/lib/node_modules                                      /storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async                                      .js:607:21
storjshare-0 (err):     at /home/osmc/.nvm/versions/node/v4.4.4/lib/node_modules                                      /storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async                                      .js:246:17
storjshare-0 (err):     at iterate (/home/osmc/.nvm/versions/node/v4.4.4/lib/nod                                      e_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/                                      lib/async.js:146:13)
storjshare-0 (err):     at async.eachSeries (/home/osmc/.nvm/versions/node/v4.4.                                      4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modul                                      es/async/lib/async.js:162:9)
storjshare-0 (err):     at _asyncMap (/home/osmc/.nvm/versions/node/v4.4.4/lib/n                                      ode_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/asyn                                      c/lib/async.js:245:13)
storjshare-0 (err): Error: socket hang up
storjshare-0 (err):     at createHangUpError (_http_client.js:200:15)
storjshare-0 (err):     at Socket.socketOnEnd (_http_client.js:292:23)
storjshare-0 (err):     at emitNone (events.js:72:20)
storjshare-0 (err):     at Socket.emit (events.js:166:7)
storjshare-0 (err):     at endReadableNT (_stream_readable.js:913:12)
storjshare-0 (err):     at nextTickCallbackWith2Args (node.js:442:9)
storjshare-0 (err):     at process._tickDomainCallback (node.js:397:17)
```

### Steps to Reproduce

Unable to reproduce yet.

**Comment by bookchin** [comment]
Strange, until this can be reproduced, we will add some error handling here: https://github.com/Storj/core/blob/master/lib/keypair.js#L78

**Comment by deadgray** [comment]
```
/home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/bitcore-lib/lib/crypto/point.js:112

   throw new Error('Invalid y value for curve.');

   ^



Error: Invalid y value for curve.

   at Point.validate (/home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/bitcore-lib/lib/crypto/point.js:112:11)

   at new PublicKey (/home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/bitcore-lib/lib/publickey.js:53:14)

   at Function.PublicKey.fromPoint (/home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/bitcore-lib/lib/publickey.js:250:10)

   at ECDSA.toPublicKey (/home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/bitcore-lib/lib/crypto/ecdsa.js:155:26)

   at FarmerInterface.Network._verifySignature (/home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:522:49)

   at /home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:496:10

   at FarmerInterface.Network._validateContact (/home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:467:3)

   at FarmerInterface.Network._verifyMessage (/home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:480:8)

   at /home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:607:21

   at /home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:246:17

   at iterate (/home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:146:13)

   at async.eachSeries (/home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:162:9)

   at _asyncMap (/home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:245:13)

   at Object.mapSeries (/home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:228:23)

   at Object.async.series (/home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:605:19)

   at Transport.RPC._trigger (/home/storj/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/lib/rpc.js:300:9)
```
Error reproduced itself, -CLI running few hours, core 3.0.4.

**Comment by littleskunk** [comment]
The error message is a littlebit different but at the end the same code block: https://docs.omniref.com/js/npm/bitcore/0.8.1/symbols/Point%23validate

**Comment by bookchin** [comment]
Moved here https://github.com/Storj/core/issues/356#issuecomment-241195576

**Comment by Puychack** [comment]
A nearly the same but different error message here :
StorjShare: 6.0.1
Core:       3.0.4
Protocol:   0.8.0

Error: Invalid y value for curve.
    at Point.validate (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/bitcore-lib/lib/crypto/point.js:112:11)
    at new PublicKey (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/bitcore-lib/lib/publickey.js:53:14)
    at Function.PublicKey.fromPoint (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/bitcore-lib/lib/publickey.js:250:10)
    at ECDSA.toPublicKey (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/bitcore-lib/lib/crypto/ecdsa.js:155:26)
    at Message.verify (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/bitcore-message/lib/message.js:98:25)
    at FarmerInterface.Network._verifySignature (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:524:18)
    at /home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:496:10
    at FarmerInterface.Network._validateContact (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:467:3)
    at FarmerInterface.Network._verifyMessage (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:480:8)
    at /home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:607:21
    at /home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:246:17
    at iterate (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:146:13)
    at async.eachSeries (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:162:9)
    at _asyncMap (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:245:13)
    at Object.mapSeries (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:228:23)
    at Object.async.series (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:605:19)

I assume it is resolved with https://github.com/Storj/core/issues/356
