### ISSUE TITLE
Farmer.db io error

### ISSUE THREAD

**Issue by pmwoodward3** [Storj/storjshare-cli#144]
On the newest release, tried getting it to work on 3 different linux servers and all three had the same issue.

```
 [...]  > Unlock your private key to start storj  >  **********

{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-08-03T18:22:54.667Z"}
{"level":"info","message":"node created with nodeID 08de1dae9718ea41f2750d681dcb72f71fe5477c","timestamp":"2016-08-03T18:22:54.735Z"}
{"level":"info","message":"resolving seeds from https://api.storj.io","timestamp":"2016-08-03T18:22:54.737Z"}

events.js:160
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: /storjshare/farmer/farmer.db: Invalid argument
    at /usr/lib/node_modules/storjshare-cli/node_modules/levelup/lib/levelup.js:119:34
    at /usr/lib/node_modules/storjshare-cli/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
/ # storjshare --version
StorjShare: 5.0.1
Core:       2.0.7
Protocol:   0.7.1
```

Same issue as #71

**Comment by brad-pea** [comment]
Just set up a new Linux box and getting this same error when trying run storjshare-cli to a mounted cifs server ...

Works fine when running to a local directory, but crashes out on a mounted directory with the above error .. same as issue #71 

Cheers.

**Comment by bookchin** [comment]
See https://github.com/Level/levelup/issues/222 for more information on this and workarounds
