### ISSUE TITLE
TypeError: Cannot read property 'keypath' of undefined

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#158]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Storjshare:  6.0.1
Core:          3.0.4
Protocol:    0.8.0
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior

Code to run without throwing errors.

### Actual Behavior

TypeError: Cannot read property 'keypath' of undefined
    at Command.start (/usr/lib64/node_modules/storjshare-cli/bin/storjshare.js:70:41)
    at Command.listener (/usr/lib64/node_modules/storjshare-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/usr/lib64/node_modules/storjshare-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/lib64/node_modules/storjshare-cli/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/lib64/node_modules/storjshare-cli/bin/storjshare.js:339:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. This is occurring on a number of the 100 nodes running on this server.  All config.json files were programatically created and SHOULD be consistent, with many verified as legit by manually starting their node.  Since no identifying error (in terms of which config.json is being processed) is provided, manual checking of the config.json is not possible.  Debugging traces have been added to the restart script to help identify...
2. ...
3. ...

**Comment by bookchin** [comment]
@aleitner any idea?

**Comment by 1credit** [comment]
Found it, my stupid.  Recently changed the "loglevel": 3 to "loglevel: 0"...

**Comment by bookchin** [comment]
Ah invalid JSON, okay good.
