### ISSUE TITLE
Crash with Error

### ISSUE THREAD

**Issue by Puychack** [Storj/storjshare-cli#161]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 6.0.1
Core:       3.0.4
Protocol:   0.8.0
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior

Shoud not crash

### Actual Behavior

Storjshare crashed with error message : 
Error
    at WebSocket.<anonymous> (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/lib/data-channels/readable-stream.js:29:26)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at WebSocket.cleanupWebsocketResources (/home/bigminer/.nvm/versions/node/v4.4.7/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/ws/lib/WebSocket.js:950:8)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. crashes happen every few hours since uprade to v6.0.1

**Comment by bookchin** [comment]
Looks like this might be related to mirroring.
