### ISSUE TITLE
crypto.js:70 - this._handle.update(data, encoding) - TypeError: Not a string or buffer

### ISSUE THREAD

**Issue by bsom** [Storj/storjshare-cli#189]
### Package Versions

Replace the values below using the output from `storjshare --version`.

StorjShare 7.0.0
Core 4.0.0
Protocol 0.9.0

Replace the values below using the output from `node --version`.

v4.4.4

### Expected Behavior

Client run without crashing randomly with a TypeError.

### Actual Behavior

{"level":"info","message":"sending PUBLISH message to {\"userAgent\":\"4.0.0\",\"protocol\":\"0.9.0\",\"address\":\"storj01.prybil.com\",\"port\":4000,\"nodeID\":\"34c3c42955e989a9cc43ced91250372f99437678\",\"lastSeen\":1475966310213}","timestamp":"2016-10-08T22:38:30.213Z"}
crypto.js:70
  this._handle.update(data, encoding);
               ^

TypeError: Not a string or buffer
    at TypeError (native)
    at Hash.update (crypto.js:70:16)
    at Object.module.exports.hashKey (/Users/bsom/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/utils.js:45:44)
    at Object.module.exports.coerceKeyOrIndex (/Users/bsom/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/utils.js:60:28)
    at _getStat (/Users/bsom/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/b-table.js:193:21)
    at /Users/bsom/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:1069:13
    at replenish (/Users/bsom/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:884:21)
    at /Users/bsom/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:888:13
    at _asyncMap (/Users/bsom/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:1067:9)
    at Object.mapLimit (/Users/bsom/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:1151:20)
    at Btable.stat (/Users/bsom/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/b-table.js:213:9)
    at /Users/bsom/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/storage/adapters/embedded.js:173:16

### Steps to Reproduce

Reproduction is haphazard at best.  It seems to happen randomly on two different farmers I am running.  Sometimes it takes a day, sometimes it takes 5 minutes.

**Comment by bookchin** [comment]
looks like a bad contract (includes an invalid data hash) and we aren't performing validation before we run the key through the kfs router.

**Comment by bsom** [comment]
It's back.....?

crypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at Object.module.exports.hashKey (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/utils.js:45:44)
    at Object.module.exports.coerceKeyOrIndex (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/utils.js:60:28)
    at _getStat (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/b-table.js:193:21)
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1156:9
    at replenish (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1030:17)
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1034:9
    at _asyncMap (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1154:5)
    at Object.mapLimit (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1240:16)
    at Btable.stat (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/b-table.js:213:9)
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/storage/adapters/embedded.js:173:16

**Comment by niko-mit-k** [comment]
I have the same problem today.

`storjshare --version`
StorjShare: 7.0.3
Core:       4.1.0
Protocol:   0.9.1

`node --version`
v4.4.4


{"level":"info","message":"sending PUBLISH message to {\"userAgent\":\"4.1.0\",\"protocol\":\"0.9.1\",\"address\":\"STORJ-CLUS-099.storj.space\",\"port\":4062,\"nodeID\":\"2fee360ffc8d67cd0026ab6fbcbe2abfd5e7a394\",\"lastSeen\":1478346240776}","timestamp":"2016-11-05T11:44:00.776Z"}
crypto.js:70
  this._handle.update(data, encoding);
               ^

TypeError: Not a string or buffer
    at TypeError (native)
    at Hash.update (crypto.js:70:16)
    at Object.module.exports.hashKey (/Users/user/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/utils.js:45:44)
    at Object.module.exports.coerceKeyOrIndex (/Users/user/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/utils.js:60:28)
    at _getStat (/Users/user/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/b-table.js:193:21)
    at /Users/user/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:1156:9
    at replenish (/Users/user/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:1030:17)
    at /Users/user/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:1034:9
    at _asyncMap (/Users/user/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:1154:5)
    at Object.mapLimit (/Users/user/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:1240:16)
    at Btable.stat (/Users/user/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/b-table.js:213:9)
    at /Users/user/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/storage/adapters/embedded.js:173:16
user@Users-MBP-2:~$

**Comment by aryeharmon** [comment]
having same issue
