### ISSUE TITLE
not implemented

### ISSUE THREAD

**Issue by Behoston** [Storj/storjshare-cli#201]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 7.0.1
Core:       4.0.2
Protocol:   0.9.0
```

Replace the values below using the output from `node --version`.

```
v0.10.25
```

### Expected Behavior
Working

### Actual Behavior

```

{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-10-13T21:06:52.086Z"}
{"level":"warn","message":"you are not publicly reachable, trying traversal strategies...","timestamp":"2016-10-13T21:06:52.114Z"}

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: not implemented
    at Writable._write (_stream_writable.js:321:6)
    at doWrite (_stream_writable.js:223:10)
    at writeOrBuffer (_stream_writable.js:213:5)
    at Writable.write (_stream_writable.js:180:11)
    at WebSocket.<anonymous> (/home/behoston/WebstormProjects/storjshare-cli/node_modules/myspeed/lib/client.js:54:18)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.onbinary (/home/behoston/WebstormProjects/storjshare-cli/node_modules/myspeed/node_modules/ws/lib/WebSocket.js:848:10)
    at /home/behoston/WebstormProjects/storjshare-cli/node_modules/myspeed/node_modules/ws/lib/Receiver.js:628:18
    at /home/behoston/WebstormProjects/storjshare-cli/node_modules/myspeed/node_modules/ws/lib/Receiver.js:368:7
    at /home/behoston/WebstormProjects/storjshare-cli/node_modules/myspeed/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:274:3)
    at onwrite (_stream_writable.js:266:7)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at afterTransform (_stream_transform.js:99:5)
    at TransformState.afterTransform (_stream_transform.js:74:12)
    at Zlib.callback (zlib.js:451:5)

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run on default parameters (with enabled telemetry)
2. In private network
3. Just start...

**Comment by bookchin** [comment]
You are running an ancient version of node. Only 4.x.x is supported.
