### ISSUE TITLE
invalid nodeId

### ISSUE THREAD

**Issue by deadgray** [Storj/storjshare-cli#202]
### Package Versions

```
StorjShare: 7.0.1
Core:       4.0.4
Protocol:   0.9.0

```

Replace the values below using the output from `node --version`.

```
4.5 LTS
```

### Expected Behavior

Do not crash ofc :-)
### Actual Behavior

Crash

```
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Invalid nodeID was supplied
    at Contact (/home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/lib/contact.js:27:3)
    at Contact.AddressPortContact (/home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/lib/contacts/address-port-contact.js:28:11)
    at new Contact (/home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/contact.js:26:35)
    at FarmerInterface.Network._createContact (/home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:363:10)
    at FarmerInterface.Network.connect (/home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:352:33)
    at /home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:250:12
    at iteratee (/home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/async/lib/async.js:449:17)
    at iterate (/home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/async/lib/async.js:262:13)
    at /home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/async/lib/async.js:274:29
    at /home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/async/lib/async.js:44:16
    at /home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/async/lib/async.js:454:21
    at /home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:253:11
    at /home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/lib/node.js:121:14
    at /home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:541:30
    at /home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/lib/router.js:509:14
    at /home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/lib/router.js:220:14

```

### Steps to Reproduce

Run farmer
Wait

**Comment by bookchin** [comment]
Do you have manually configured seeds? If so can you paste them here?

**Comment by bookchin** [comment]
Closing due to inactivity. Check that if you have manually configured seeds, that it contains valid node IDs.
