### ISSUE TITLE
item.shard.destroy is not a function

### ISSUE THREAD

**Issue by Behoston** [Storj/storjshare-cli#203]
### Package Versions

```
StorjShare:  7.0.1
Core:        4.0.2
Protocol:    0.9.0
Node:       v4.5.0
```

### Expected Behavior
Not throw exception

### Actual Behavior
```
root@Debian1:~/.pm2/logs# cat storjshare-error-0.log
TypeError: item.shard.destroy is not a function
    at PassThrough.<anonymous> (/root/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/data-channels/server.js:260:20)
    at emitNone (events.js:72:20)
    at PassThrough.emit (events.js:166:7)
    at endReadableNT (/root/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/readable-stream/lib/_stream_readable.js:922:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
```

### Steps to Reproduce

Don't know

**Comment by bookchin** [comment]
Fixed in storj-lib@4.0.4
