### ISSUE TITLE
crypto.js:74 this._handle.update(data, encoding); TypeError: Data must be a string or a buffer

### ISSUE THREAD

**Issue by bsom** [Storj/storjshare-cli#205]
### Package Versions

Replace the values below using the output from `storjshare --version`.

StorjShare: 7.0.1
Core: 4.0.6
Protocol 0.9.1

Replace the values below using the output from `node --version`.

v6.7.0
### Expected Behavior

Execute and stay running.
### Actual Behavior

Crashes repeatedly on one instance I have running with the following:
crypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at Object.module.exports.hashKey (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/utils.js:45:44)
    at Object.module.exports.coerceKeyOrIndex (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/utils.js:60:28)
    at _getStat (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/b-table.js:193:21)
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1156:9
    at replenish (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1030:17)
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1034:9
    at _asyncMap (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1154:5)
    at Object.mapLimit (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1240:16)
    at Btable.stat (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/b-table.js:213:9)
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/storage/adapters/embedded.js:173:16
### Steps to Reproduce

This instance of storjshare started exhibiting this behavior yesterday.  It has since restarted over 200 times, running for about three minutes per instance.

**Comment by bookchin** [comment]
duplicate https://github.com/Storj/kfs/issues/36

**Comment by dannypule** [comment]
Was getting this error also:

```
86% hashingcrypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
```

I removed the following line of code from an index.ts because the file location had changed:
`export { CounterService } from './counter/counter.service';`

Then got a new error:
`"ERROR in C:/git/demo/src/app/app.module.ts (22,32): File 'C:/git/demo/src/app/shared/services/index.ts' is not a module."`

This was easy to solve in app.module.ts by changing the reference to `import { CounterService } from './counter/services/counter.service';`

rather than `import { CounterService } from './shared/services';` which no longer existed
