### ISSUE TITLE
Module version mismatch. Expected 48, got 46.

### ISSUE THREAD

**Issue by subwolf** [Storj/storjshare-cli#213]
node.js v6.9.1

```
/usr/local/lib
└─┬ storjshare-cli@8.0.0 
  └─┬ storj-lib@5.0.1 
    ├── jsen@0.6.4  (git://github.com/bugventure/jsen.git#9e57a9d653ff4ea47d364fc37da0f1659bfb8e89)
    ├── kad-quasar@1.0.2 
    ├── kfs@2.3.0 
    └── ntp-client@0.5.5  (git://github.com/bookchin/node-ntp-client.git#64a1d2318284578b90f388565de7c4b5a2441233)
```

Trying to run storjshare-cli through pm2...

```
storjshare-1 Error: Module version mismatch. Expected 48, got 46.
storjshare-1     at Error (native)
storjshare-1     at Object.Module._extensions..node (module.js:597:18)
storjshare-1     at Module.load (module.js:487:32)
storjshare-1     at tryModuleLoad (module.js:446:12)
storjshare-1     at Function.Module._load (module.js:438:3)
storjshare-1     at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
storjshare-1     at Module.require (module.js:497:17)
storjshare-1     at require (internal/module.js:20:19)
storjshare-1     at bindings (/usr/local/lib/node_modules/storjshare-cli/node_modules/leveldown/node_modules/bindings/bindings.js:76:44)
storjshare-1     at Object.<anonymous> (/usr/local/lib/node_modules/storjshare-cli/node_modules/leveldown/leveldown.js:4:46)
```

Synology DS1515+ with DSM V6.1, running chroot from debian shell.

**Comment by littleskunk** [comment]
Solved but not release: https://github.com/Storj/storjshare-cli/pull/209

**Comment by bookchin** [comment]
You just need to reinstall or `npm rebuild` from the project directory - the native bindings are compiled against the previous node version you were using.
