### ISSUE TITLE
TypeError:  Downloader.unpipe is not a function

### ISSUE THREAD

**Issue by CJClaude** [Storj/storjshare-cli#225]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 9.0.0  (@next version as of 12/1/16)
Core:       6.0.0
Protocol:   1.0.0

```

Replace the values below using the output from `node --version`.

```
V6.9.1
```

### Expected Behavior

Error free run

### Actual Behavior

With 512 nodes running against testnet, I'm seeing:

TypeError: downloader.unpipe is not a function
    at Request._onStreamError (/usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/protocol.js:324:18)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/lib64/node_modules/storjshare-cli/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Appear every so often.  Perhaps 1 in 10 nodes are experiencing this.
```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by bookchin** [comment]
Thanks: https://github.com/Storj/core/pull/573
