### ISSUE TITLE
AssertionError: Invalid nodeID was supplied

### ISSUE THREAD

**Issue by CJClaude** [Storj/storjshare-cli#226]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 9.0.0
Core:       6.0.1
Protocol:   1.0.0
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Nodes run without errors.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

This is randomly happening after starting up nodes.  The error does cause the node to fail.  With 512 running nodes, I'm seeing this errror several times a minute.

Key log entry (before and after included later):

{"level":"info","message":"attempting to join network via storj://[object Object]:55046/c986eeaef5d5084a379e8f017fff02322211ea67","timestamp":"2016-12-02T15:39:59.909Z"}

Note the [object Object] instead of a URL.

Console output:

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Invalid nodeID was supplied
    at Contact (/usr/lib64/node_modules/storjshare-cli/node_modules/kad/lib/contact.js:27:3)
    at Contact.AddressPortContact (/usr/lib64/node_modules/storjshare-cli/node_modules/kad/lib/contacts/address-port-contact.js:28:11)
    at new Contact (/usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/contact.js:42:35)
    at FarmerInterface.Network._createContact (/usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:377:10)
    at FarmerInterface.Network.connect (/usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:366:33)
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:268:12
    at iteratee (/usr/lib64/node_modules/storjshare-cli/node_modules/async/lib/async.js:449:17)
    at iterate (/usr/lib64/node_modules/storjshare-cli/node_modules/async/lib/async.js:262:13)
    at /usr/lib64/node_modules/storjshare-cli/node_modules/async/lib/async.js:274:29
    at /usr/lib64/node_modules/storjshare-cli/node_modules/async/lib/async.js:44:16
    at /usr/lib64/node_modules/storjshare-cli/node_modules/async/lib/async.js:454:21
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:271:11
    at /usr/lib64/node_modules/storjshare-cli/node_modules/kad/lib/node.js:128:14
    at /usr/lib64/node_modules/storjshare-cli/node_modules/kad/node_modules/async/lib/async.js:541:30
    at /usr/lib64/node_modules/storjshare-cli/node_modules/kad/lib/router.js:539:14
    at /usr/lib64/node_modules/storjshare-cli/node_modules/kad/lib/router.js:234:14

Snippet of a log file showing activity before and the restart after:

{"level":"warn","message":"rpc call e3d1d70425c1e7752460c63d6637ebbabf2b2647 timed out","timestamp":"2016-12-02T15:38:44.839Z"}
{"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `e3d1d70425c1e7752460c63d6637ebbabf2b2647` timed out","timestamp":"2016-12-02T15:38:44.839Z"}
{"level":"warn","message":"failed to connect to seed storj://81.196.249.172:18100/686dbbfb9abb11776960fa9d26bd80096f385a24","timestamp":"2016-12-02T15:38:44.839Z"}
{"level":"info","message":"attempting to join network via storj://driveone.storj.host:43206/a7f8436046762e040dc6671132c1f986ed6b4a35","timestamp":"2016-12-02T15:38:44.839Z"}
{"level":"info","message":"sending FIND_NODE message to {\"userAgent\":\"6.0.1\",\"protocol\":\"1.0.0\",\"address\":\"driveone.storj.host\",\"port\":43206,\"nodeID\":\"a7f8436046762e040dc6671132c1f986ed6b4a35\",\"lastSeen\":1480693124840}","timestamp":"2016-12-02T15:38:44.840Z"}
{"level":"warn","message":"rpc call dfdd532bc3c6c630aa941707efb067ad0f449dfd timed out","timestamp":"2016-12-02T15:39:14.858Z"}
{"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `dfdd532bc3c6c630aa941707efb067ad0f449dfd` timed out","timestamp":"2016-12-02T15:39:14.859Z"}
{"level":"warn","message":"failed to connect to seed storj://driveone.storj.host:43206/a7f8436046762e040dc6671132c1f986ed6b4a35","timestamp":"2016-12-02T15:39:14.859Z"}
{"level":"info","message":"attempting to join network via storj://138.201.13.159:4036/b86c327cdd4e7388f16e507702f9af001bb54f9e","timestamp":"2016-12-02T15:39:14.859Z"}
{"level":"info","message":"sending FIND_NODE message to {\"userAgent\":\"6.0.1\",\"protocol\":\"1.0.0\",\"address\":\"138.201.13.159\",\"port\":4036,\"nodeID\":\"b86c327cdd4e7388f16e507702f9af001bb54f9e\",\"lastSeen\":1480693154859}","timestamp":"2016-12-02T15:39:14.859Z"}
{"level":"warn","message":"rpc call 91efcf0f3f1b631d7f7631dd8b4987dbb96ad87f timed out","timestamp":"2016-12-02T15:39:44.892Z"}
{"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `91efcf0f3f1b631d7f7631dd8b4987dbb96ad87f` timed out","timestamp":"2016-12-02T15:39:44.892Z"}
{"level":"warn","message":"failed to connect to seed storj://138.201.13.159:4036/b86c327cdd4e7388f16e507702f9af001bb54f9e","timestamp":"2016-12-02T15:39:44.892Z"}
{"level":"info","message":"attempting to join network via storj://ns301726.ip-94-23-54.eu:4000/c12098aa4350cacc83737b273d8fe05950668815","timestamp":"2016-12-02T15:39:44.892Z"}
{"level":"info","message":"sending FIND_NODE message to {\"userAgent\":\"6.0.1\",\"protocol\":\"1.0.0\",\"address\":\"ns301726.ip-94-23-54.eu\",\"port\":4000,\"nodeID\":\"c12098aa4350cacc83737b273d8fe05950668815\",\"lastSeen\":1480693184893}","timestamp":"2016-12-02T15:39:44.893Z"}
{"level":"warn","message":"error returned from remote host: socket hang up","timestamp":"2016-12-02T15:39:44.963Z"}
{"level":"warn","message":"missing or empty reply from contact","timestamp":"2016-12-02T15:39:44.963Z"}
{"level":"warn","message":"rpc call 9caaf4c61b2ef81e4210a2a0a9c38c1a5f427756 timed out","timestamp":"2016-12-02T15:39:59.908Z"}
{"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `9caaf4c61b2ef81e4210a2a0a9c38c1a5f427756` timed out","timestamp":"2016-12-02T15:39:59.908Z"}
{"level":"warn","message":"failed to connect to seed storj://ns301726.ip-94-23-54.eu:4000/c12098aa4350cacc83737b273d8fe05950668815","timestamp":"2016-12-02T15:39:59.908Z"}
{"level":"info","message":"attempting to join network via storj://[object Object]:55046/c986eeaef5d5084a379e8f017fff02322211ea67","timestamp":"2016-12-02T15:39:59.909Z"}
tail: port6000.log: file truncated
{"level":"warn","message":"your address is public and traversal strategies are disabled","timestamp":"2016-12-02T15:45:00.863Z"}
{"level":"info","message":"node created with nodeID ededce6252029b0bf8a4ac40f755ad19111f4d7f","timestamp":"2016-12-02T15:45:00.891Z"}
{"type":"info","message":"telemetry report {\"storage\":{\"free\":167827915674,\"used\":107049991270},\"contact\":{\"userAgent\":\"6.0.1\",\"protocol\":\"1.0.0\",\"address\":\"pspoe.carpenter-farms.us\",\"port\":6000,\"nodeID\":\"ededce6252029b0bf8a4ac40f755ad19111f4d7f\",\"lastSeen\":1480693500806},\"payment\":\"1CqdxZemsFmg1A9fm3y1hduwqF5wzBAyKJ\"}","timestamp":"2016-12-02T15:45:01.300Z"}
{"level":"info","message":"clock is synchronized with ntp, delta: 30","timestamp":"2016-12-02T15:45:01.351Z"}
{"level":"info","message":"resolving seeds from http://server025.storj.dk","timestamp":"2016-12-02T15:45:01.370Z"}
{"level":"info","message":"attempting to join network via storj://server022.storj.dk:5010/04a697072e54e4f54bbb8ab9453b898de0c4cecc","timestamp":"2016-12-02T15:45:06.481Z"}
{"level":"info","message":"sending FIND_NODE message to {\"userAgent\":\"6.0.1\",\"protocol\":\"1.0.0\",\"address\":\"server022.storj.dk\",\"port\":5010,\"nodeID\":\"04a697072e54e4f54bbb8ab9453b898de0c4cecc\",\"lastSeen\":1480693506489}","timestamp":"2016-12-02T15:45:06.489Z"}


```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by CJClaude** [comment]
Switched from using http://server025.storj.dk to https://api.staging.storj.io and have not seen the problem since.  Only been a short while, but they were coming in at several a minute.

**Comment by CJClaude** [comment]
Switched back to storj.dk this morning and the errors immediately reappeared.  @bookchin - please tell @th$van what you did to fix your side! <smile>

**Comment by bookchin** [comment]
Didn't do anything to fix over here. Looks like a bad configuration of the `address` property. I know @th3van has a script that patches parts of the code for various purposes, so it's possible that those no longer work as expected. 

But I have no insight as to why his setup is behaving this way.

**Comment by bookchin** [comment]
Either way we need to implement safer validation to prevent this from crashing nodes.

**Comment by Th3Van** [comment]
Thanks for the heads-up @CJClaude,

server025.storj.dk should be working fine. I'm currently testing the latest storjshare-cli (9.0.0) client on server011, (Using STORJ_BRIDGE=http://seedpool002.storj.dk) and its been working fine since I fired it up a few days ago.
The `attempting to join network via storj://[object Object]:55046/b231231...` problem was one of the reasons I created seedpool001 and seedpool002.
I was having the exact same problem with farmers/bridges occasionally falling due to the "[object object]" problem, when i was cranking up like +100 nodes, but with your +1000 nodes the "object" problem would escalate even further!

The seedpool-script greps a few pages from api.storj.io/contacts + a few /contacts pages from a couple of the storj.dk servers.
The list are then filtered and things like 192.168./172.16./10./[object./0.0.0.0 etc. are removed.
- http://seedpool001.storj.dk/contacts - only lists nodes using protocol v0.10.0
- http://seedpool002.storj.dk/contacts - only lists nodes using protocol v1.0.0 

Both seedpool servers are ment to be used by the storj.dk servers to offload api.storj.io, but farmers are welcome to use them if they like.
Please note, if using the environment variable STORJ_BRIDGE=http://seedpool001.storj.dk, "exchange reports" will be send to the speedpool servers but will be ignored/dropped.

Looking at the contact list @ server025, quite a few "[object object]" nodes are still "active" :

```
root@Server010:~# date -u
Sun Dec  4 06:00:20 UTC 2016
root@Server010:~# curl -s "http://server025.storj.dk/contacts" | jq --raw-output -c  '.[] | {protocol,userAgent,nodeID,address,port,lastSeen}' | grep "bject"
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"16e57a246b8825514308d92067fde62f14508b34","address":"[object Object]","port":56571,"lastSeen":"2016-12-04T05:59:15.656Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"15f6e770ee30f5ee576445d862a0183f20b3faf8","address":"[object Object]","port":64791,"lastSeen":"2016-12-04T05:58:22.234Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"61ae384f4de9623f4b8e0f61b9a5b5053d28e73b","address":"[object Object]","port":17468,"lastSeen":"2016-12-04T05:55:32.429Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"bc037e5e05e206818c8475734cf8ed6f6f13a29e","address":"[object Object]","port":60086,"lastSeen":"2016-12-04T05:48:48.108Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"9ad7b50716c92d531ac9f43d97bb25459846a187","address":"[object Object]","port":4001,"lastSeen":"2016-12-04T05:47:56.514Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"c986eeaef5d5084a379e8f017fff02322211ea67","address":"[object Object]","port":55046,"lastSeen":"2016-12-04T03:20:26.652Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"8b7a99f556a367d41006014f1ccc484b128514c3","address":"[object Object]","port":12935,"lastSeen":"2016-12-04T01:44:23.826Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"bddabb42b7ba299b7878bca11ecb8872c67b90b6","address":"[object Object]","port":40369,"lastSeen":"2016-12-03T14:42:04.987Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"235ba39a081e54b4d59190ac20083d9ee872c6a3","address":"[object Object]","port":54756,"lastSeen":"2016-12-03T14:41:11.458Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"11306e785d119d00489170f1ab472d4df80b35ab","address":"[object Object]","port":32729,"lastSeen":"2016-12-03T14:40:21.568Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"ea0e3b77a4c69a4e1a7a15343fc82e26bdec1104","address":"[object Object]","port":34690,"lastSeen":"2016-12-03T14:28:15.374Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"47a78e3994fc235510b0a9c515d5989b6811c5e5","address":"[object Object]","port":5887,"lastSeen":"2016-12-03T14:27:35.499Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"3baed6fb2ca2949e72f30c3f594b037afc693e11","address":"[object Object]","port":4000,"lastSeen":"2016-12-03T14:16:24.702Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"8f23a20f1b3b96a3a116fd287672b0aeefdd411b","address":"[object Object]","port":27820,"lastSeen":"2016-12-03T13:20:41.630Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"28737dca72716993600de4dd9935e74f87d3cc02","address":"[object Object]","port":8785,"lastSeen":"2016-12-02T23:28:15.330Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"1bdc26691ad609dadf393ada56c8ee1038d87caa","address":"[object Object]","port":11612,"lastSeen":"2016-11-30T20:31:38.344Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"092422ccae22bea071ffff7656b6b7ff6f4f520c","address":"[object Object]","port":18260,"lastSeen":"2016-11-29T22:47:01.132Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"15b23f1f494389a1ee27712eeb1bcbe8528c901b","address":"[object Object]","port":36463,"lastSeen":"2016-11-27T09:41:12.030Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"64d58920c415f33acfaa1134654061a36b7c9a4d","address":"[object Object]","port":36428,"lastSeen":"2016-11-26T17:21:01.174Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"3e662ab4648380ab74c1521b6761dc0711a310ed","address":"[object Object]","port":40972,"lastSeen":"2016-11-22T21:49:06.125Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"7d0efa14d6ff3f861125d7114eb1984337c38a45","address":"[object Object]","port":45956,"lastSeen":"2016-11-22T04:39:01.133Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"27e528c0e42a6f2bcdd341fc70a660ec35de8227","address":"[object Object]","port":59244,"lastSeen":"2016-11-22T03:57:04.427Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"5141d840306452faac6a6a2e894ff3ef144aa43f","address":"[object Object]","port":61608,"lastSeen":"2016-11-20T08:23:03.985Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"fedabdb5e68f2dc1df357134fb33ce8d00be3696","address":"[object Object]","port":43741,"lastSeen":"2016-11-19T08:25:23.172Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"47dfb05fc2327de7340121aac112270b4e158311","address":"[object Object]","port":8000,"lastSeen":"2016-11-17T16:22:07.414Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"a0d5f7cd9cc9b4a74fd3ddc03fed46a44376498d","address":"[object Object]","port":51157,"lastSeen":"2016-11-17T08:49:06.135Z"}
{"protocol":"0.10.0","userAgent":"5.0.1","nodeID":"be7c5955bf506740901e512593c3de65640a0889","address":"[object Object]","port":5584,"lastSeen":"2016-11-11T13:53:48.321Z"}
```

//Th3Van

**Comment by bookchin** [comment]
Ah so this looks like a two-sided issue. It looks like misconfiguration of a storjshare node that the bridges then store and give to other storjshare nodes. I think adding better validation on both sides will fix this.

**Comment by CJClaude** [comment]
Just pointed to seedpool002 and restarting ~1100 nodes.  Other than failure to connect to my own nodes (which are restarting), so far, so good.

Seeing a few of the lock problems reported in another issue (example):

      throw er; // Unhandled 'error' event
      ^

Error: IO error: lock /storj/node84/sharddata.kfs/244.s/LOCK: already held by process
    at Error (native)

**Comment by Th3Van** [comment]
Also looking fine form here  :
```
66.128.118.34 - - [05/Dec/2016:00:30:11 +0100] "seedpool002.storj.dk/reports/exchanges" 404 481 "POST /reports/exchanges HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:11 +0100] "seedpool002.storj.dk/contacts" 200 12446 "GET /contacts?connected=true&__nonce=67ed66b0-a197-4d4d-81e4-6b1b3855573b HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:13 +0100] "seedpool002.storj.dk/contacts" 200 12445 "GET /contacts?connected=true&__nonce=a90ea443-a1bb-47d3-99b5-2d7b0b73c8e4 HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:13 +0100] "seedpool002.storj.dk/contacts" 200 12449 "GET /contacts?connected=true&__nonce=9ea884dd-888a-411d-9356-da97ecde2bd0 HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:14 +0100] "seedpool002.storj.dk/contacts" 200 12448 "GET /contacts?connected=true&__nonce=6e57008f-e8f9-4c45-bc26-cb841a7d6a4e HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:15 +0100] "seedpool002.storj.dk/reports/exchanges" 404 481 "POST /reports/exchanges HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:15 +0100] "seedpool002.storj.dk/contacts" 200 12447 "GET /contacts?connected=true&__nonce=873ae72e-1abb-43b1-bc60-f8c7c812a231 HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:15 +0100] "seedpool002.storj.dk/contacts" 200 12449 "GET /contacts?connected=true&__nonce=2c7e7855-ae9c-42a4-9794-65e22f8381bc HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:15 +0100] "seedpool002.storj.dk/contacts" 200 12439 "GET /contacts?connected=true&__nonce=e2ce2457-f876-4cc8-8b20-298d81007ebd HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:15 +0100] "seedpool002.storj.dk/contacts" 200 12440 "GET /contacts?connected=true&__nonce=81a1aaa1-5983-4fc3-9ebc-a2cc7662b996 HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:16 +0100] "seedpool002.storj.dk/contacts" 200 12456 "GET /contacts?connected=true&__nonce=25e77258-7496-473b-bd60-219c9d46e80c HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:16 +0100] "seedpool002.storj.dk/contacts" 200 12428 "GET /contacts?connected=true&__nonce=bfa63c14-351d-49fd-8766-f69d83152052 HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:16 +0100] "seedpool002.storj.dk/reports/exchanges" 404 481 "POST /reports/exchanges HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:17 +0100] "seedpool002.storj.dk/contacts" 200 12444 "GET /contacts?connected=true&__nonce=24597eb7-debd-41e5-af85-62bad422adaf HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:17 +0100] "seedpool002.storj.dk/contacts" 200 12445 "GET /contacts?connected=true&__nonce=d2ffef13-04ac-4822-95eb-6581f2d16cdf HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:17 +0100] "seedpool002.storj.dk/contacts" 200 12423 "GET /contacts?connected=true&__nonce=4b8fcc7d-35e0-46f4-8410-68b998432727 HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:18 +0100] "seedpool002.storj.dk/contacts" 200 12432 "GET /contacts?connected=true&__nonce=43911609-a1f3-45ff-8d8d-ee61710f4f62 HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:20 +0100] "seedpool002.storj.dk/contacts" 200 12441 "GET /contacts?connected=true&__nonce=6164db2b-b36f-4d17-8eff-c074db7c124d HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:20 +0100] "seedpool002.storj.dk/reports/exchanges" 404 481 "POST /reports/exchanges HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:22 +0100] "seedpool002.storj.dk/contacts" 200 12424 "GET /contacts?connected=true&__nonce=6bd7f263-a567-402b-b016-9e24fecc2a42 HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:23 +0100] "seedpool002.storj.dk/contacts" 200 12439 "GET /contacts?connected=true&__nonce=04d78ce8-3cfa-4d44-b290-7d6d48abeac9 HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:23 +0100] "seedpool002.storj.dk/contacts" 200 12436 "GET /contacts?connected=true&__nonce=0497733f-c58c-4710-881b-756d91e7857f HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:23 +0100] "seedpool002.storj.dk/contacts" 200 12432 "GET /contacts?connected=true&__nonce=11a9c379-4f7b-45c7-9806-f65d693c59fa HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:25 +0100] "seedpool002.storj.dk/contacts" 200 12442 "GET /contacts?connected=true&__nonce=ea71474d-892b-4577-b12c-db0f567e945a HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:25 +0100] "seedpool002.storj.dk/contacts" 200 12453 "GET /contacts?connected=true&__nonce=3a691e23-e4bc-4494-a83e-96d1ca459fb2 HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:25 +0100] "seedpool002.storj.dk/contacts" 200 12431 "GET /contacts?connected=true&__nonce=b1868e6d-425d-4fde-86d9-ea682aa455fa HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:28 +0100] "seedpool002.storj.dk/contacts" 200 12452 "GET /contacts?connected=true&__nonce=01e07d36-4211-447d-a60a-6e1e631bbec9 HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:28 +0100] "seedpool002.storj.dk/contacts" 200 12442 "GET /contacts?connected=true&__nonce=061e8aa3-f94b-48df-9393-4cdf4986c238 HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:30 +0100] "seedpool002.storj.dk/reports/exchanges" 404 481 "POST /reports/exchanges HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:31 +0100] "seedpool002.storj.dk/contacts" 200 12443 "GET /contacts?connected=true&__nonce=03564d34-0b90-4cc5-8f55-37e5014d461b HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:31 +0100] "seedpool002.storj.dk/contacts" 200 12454 "GET /contacts?connected=true&__nonce=39db56b3-f788-46ac-8570-9cf9095d8d9b HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:32 +0100] "seedpool002.storj.dk/reports/exchanges" 404 481 "POST /reports/exchanges HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:34 +0100] "seedpool002.storj.dk/contacts" 200 12431 "GET /contacts?connected=true&__nonce=62aa1b55-5498-41f3-aa13-85fc75a6ca8d HTTP/1.1" "-" "-"
66.128.118.34 - - [05/Dec/2016:00:30:38 +0100] "seedpool002.storj.dk/contacts" 200 12431 "GET /contacts?connected=true&__nonce=39db22d8-abf6-474e-9a96-2c80bd5b77a7 HTTP/1.1" "-" "-"
```
