### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by krilson** [Storj/storjshare-cli#230]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Latest one (on 10th of december 2017)

storjshare --version returns an error too:

```
storjshare --version
/home/krile/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/protocol.js:294
  const {data_hash: hash, token} = params;
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/krile/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:17:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)`
```
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

Please describe the program's expected behavior.

### Actual Behavior

/home/krile/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/protocol.js:294
  const {data_hash: hash, token} = params;
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/krile/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:17:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. npm install -g storjshare-cli (on ubuntu server 14.04)
2. storjshare start

**Comment by littleskunk** [comment]
Please update to nodejs v6.9.1
