### ISSUE TITLE
Error: Failed to join the network

### ISSUE THREAD

**Issue by CJClaude** [Storj/storjshare-cli#241]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 9.0.8
Core:       6.0.11
Protocol:   1.0.0

```

Replace the values below using the output from `node --version`.

```
V6.9.1
```

### Expected Behavior

Nodes run without errors

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Currently running 270ish nodes and seeing these messages starting to appear after startup.

events.js:160
      throw er; // Unhandled 'error' event

Error: Failed to join the network
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:278:28
    at done (/usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/async/dist/async.js:2707:17)
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/async/dist/async.js:356:16
    at replenish (/usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/async/dist/async.js:877:25)
    at iterateeCallback (/usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/async/dist/async.js:867:17)
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/async/dist/async.js:840:16
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/async/dist/async.js:2720:21
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:270:11
    at /usr/lib64/node_modules/storjshare-cli/node_modules/kad/lib/node.js:128:14
    at /usr/lib64/node_modules/storjshare-cli/node_modules/kad/node_modules/async/lib/async.js:541:30
    at /usr/lib64/node_modules/storjshare-cli/node_modules/kad/lib/router.js:539:14
    at /usr/lib64/node_modules/storjshare-cli/node_modules/kad/lib/router.js:234:14
    at done (/usr/lib64/node_modules/storjshare-cli/node_modules/kad/node_modules/async/lib/async.js:132:19)
    at /usr/lib64/node_modules/storjshare-cli/node_modules/kad/node_modules/async/lib/async.js:32:16
    at /usr/lib64/node_modules/storjshare-cli/node_modules/kad/lib/router.js:225:7
    at Object.callback (/usr/lib64/node_modules/storjshare-cli/node_modules/kad/lib/router.js:265:14)

It may be signficiant that as of 9.0.8 the previouosly fought network/modem contention issue has resurfaced.  Under 9.0.7 I was able to run over 1100 nodes.  As of 9.0.8 my network becomes unresponsive (Rocket disconnects, IRC disconnects, Miners unable to reach the Internet) around 500 nodes.  This feels like a non-critical symptom of that problem (e.g.  I minor side-effect due to the few number of nodes being run).

Please note this is occuring while little network activity is happening.  I have a 200/10 connection with this traffic pattern during the errors:  http://puu.sh/sTLHT/5b3708d942.png

Likewise, I saw about 3Mbps up & down during the unresponsive incident.

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by d2s4** [comment]
Similar Problem

**Comment by MeijeSibbel** [comment]
same issue:

```
0|storjsha | {"level":"info","message":"received PING from 8a5ab7a91e857831de172a8ecf0a86044bbba170, sending PONG","timestamp":"2017-01-09T23:14:20.374Z"}
0|storjsha | {"level":"info","message":"replying to message to c9f64f825de0025616ea15e7389b924e575348f0","timestamp":"2017-01-09T23:14:20.374Z"}
0|storjsha | {"level":"info","message":"received valid message from {\"userAgent\":\"6.0.11\",\"protocol\":\"1.0.0\",\"address\":\"client015.storj.dk\",\"port\":15012,\"nodeID\":\"c061c0aed9b0102c634f3a56c7b36a3f2f09fa1d\",\"lastSeen\":1484003660736}","timestamp":"2017-01-09T23:14:20.736Z"}
0|storjsha | {"level":"warn","message":"error returned from remote host: {\"error\":\"Client cannot service request at this time\"}","timestamp":"2017-01-09T23:14:21.400Z"}
0|storjsha | {"level":"warn","message":"missing or empty reply from contact","timestamp":"2017-01-09T23:14:21.401Z"}
0|storjsha | {"level":"warn","message":"rpc call 5cde96b7a3064e98805057e324aaf05378a1b499 timed out","timestamp":"2017-01-09T23:14:31.193Z"}
0|storjsha | {"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `5cde96b7a3064e98805057e324aaf05378a1b499` timed out","timestamp":"2017-01-09T23:14:31.193Z"}
0|storjsha | {"level":"warn","message":"rpc call 1b384bb7b435a02910c59c2b4c4c65f4eca60f19 timed out","timestamp":"2017-01-09T23:14:31.194Z"}
0|storjsha | {"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `1b384bb7b435a02910c59c2b4c4c65f4eca60f19` timed out","timestamp":"2017-01-09T23:14:31.194Z"}
0|storjsha | {"level":"warn","message":"rpc call 2c99a58a958861c3df6a75c0d6779dba823084fb timed out","timestamp":"2017-01-09T23:14:31.194Z"}
0|storjsha | {"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `2c99a58a958861c3df6a75c0d6779dba823084fb` timed out","timestamp":"2017-01-09T23:14:31.195Z"}
0|storjsha | {"level":"warn","message":"failed to connect to seed storj://001s.storjlt.xyz:5601/159ca73409c9b113f7e14b2daf3873b719cd7729","timestamp":"2017-01-09T23:14:31.195Z"}
0|storjsha | Error: Failed to join the network
0|storjsha |     at C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj-lib\lib\network\index.js:278:28
0|storjsha |     at done (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj-lib\node_modules\async\dist\async.js:2707:17)
0|storjsha |     at C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj-lib\node_modules\async\dist\async.js:356:16
0|storjsha |     at replenish (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj-lib\node_modules\async\dist\async.js:877:25)
0|storjsha |     at iterateeCallback (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj-lib\node_modules\async\dist\async.js:867:17)
0|storjsha |     at C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj-lib\node_modules\async\dist\async.js:840:16
0|storjsha |     at C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj-lib\node_modules\async\dist\async.js:2720:21
0|storjsha |     at C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj-lib\lib\network\index.js:270:11
0|storjsha |     at C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\kad\lib\node.js:128:14
0|storjsha |     at C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\kad\node_modules\async\lib\async.js:541:30
0|storjsha |     at C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\kad\lib\router.js:539:14
0|storjsha |     at C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\kad\lib\router.js:234:14
0|storjsha |     at done (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\kad\node_modules\async\lib\async.js:132:19)
0|storjsha |     at C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\kad\node_modules\async\lib\async.js:32:16
0|storjsha |     at C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\kad\lib\router.js:225:7
0|storjsha |     at Object.callback (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\kad\lib\router.js:265:14)
PM2        | App [storjshare] with id [0] and pid [6108], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:storjshare id:0
PM2        | App name:storjshare id:0 online
```

**Comment by littleskunk** [comment]
Duplicate: https://github.com/kadtools/kad/issues/89
