### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 46.

### ISSUE THREAD

**Issue by contactsid** [Storj/storjshare-cli#250]
I am running a protractor test case in intellij IDEA. Here is the error log.

/usr/local/bin/node /Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/protractor/lib/cli.js CONFIG/confIDE.js
Tags: @sid
info: Proxy listening on proxyPort: 8282
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
(node:67865) DeprecationWarning: `DEBUG_FD` is deprecated. Override `debug.log` if you want to use a different log function (https://git.io/vMUyr)
[launcher] Error: Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/oracledb/lib/oracledb.js:23:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/oracledb/index.js:1:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/support/utils/db.js:6:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/support/hooks.js:2:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:63:29
    at Array.forEach (native)
    at Object.wrapper (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:62:15)
    at Object.initializer (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:23:37)
    at Object.Library (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/cucumber/lib/cucumber/support_code/library.js:118:25)
    at Object.getSupportCodeLibrary (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:10:58)
    at Object.getSupportCodeLibrary (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/cucumber/lib/cucumber/cli/configuration.js:126:32)
    at Object.getSupportCodeLibrary (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/cucumber/lib/cucumber/runtime.js:43:46)
    at Object.start (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/cucumber/lib/cucumber/runtime.js:12:37)
    at Object.run (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/cucumber/lib/cucumber/cli.js:58:15)
    at /Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/protractor-cucumber-framework/index.js:31:34
    at Function.promise (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/q/q.js:682:9)
    at /Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/protractor-cucumber-framework/index.js:24:14
    at _fulfilled (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/q/q.js:796:13)
    at /Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/q/q.js:556:49
    at runSingle (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/q/q.js:137:13)
    at flush (/Users/satapas2/Documents/Repos/cod-angular-ui/tests/acceptance/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[launcher] Process exited with error code 100

I did 'npm rebuild' as suggested in another issue. However, it did not solve.

**Comment by contactsid** [comment]
This is solved. The "Node Interpreter" variable in the intelliJ Run -> Edit Configuration was pointing to 6.9.2 however the code was build with 4.2.3. So, there was a mismatch between the code build and the protractor test run.

**Comment by littleskunk** [comment]
Did you notice this?
https://github.com/Storj/storjshare-cli#this-package-is-no-longer-maintained---please-see-storjshare-daemon
