### ISSUE TITLE
Crash on "opening gateway for [nodeID]"

### ISSUE THREAD

**Issue by redjk** [Storj/storjshare-cli#54]
Running in Docker on Synology.

### Package Versions

Replace the values below using the output from `storjshare --version`.

```
$ sudo docker run --rm -ti oreandawe/storj-farmer --version
Farmer: v3.0.2
Core:   v0.6.13
```

Replace the values below using the output from `node --version`.

```
$ sudo docker run --rm -ti --entrypoint /usr/bin/node oreandawe/storj-farmer --version
v4.3.0
```

### Expected Behavior

Please describe the program's expected behavior.

To continue as normal, and allow other users to tunnel through my node. 

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
{"level":"info","message":"opening gateway for 8147c13a37bddd5aeb84a2e32b49ffa942c6ca1d","timestamp":"2016-05-13T17:43:39.923Z"}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::4002
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at TunnelGateway.open (/usr/lib/node_modules/storjshare-cli/node_modules/storj/lib/tunnel/gateway.js:166:16)
    at TunnelServer.createGateway (/usr/lib/node_modules/storjshare-cli/node_modules/storj/lib/tunnel/server.js:109:11)
    at Protocol._handleOpenTunnel (/usr/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/protocol.js:326:39)
    at Transport.protocol (/usr/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/lib/hooks/protocol.js:33:12)
    at /usr/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:607:21
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Run as normal, and wait for someone to open a gateway through you.

**Comment by gordonwritescode** [comment]
That error indicates that port 4002 is already in use. This should never happen unless you explicitly define a gateway port range in your config. Currently, if an explicit range is defined, we aren't checking if the next port is available before opening it. We should do that, but for now I'd check to see if another service is running on 4002 and either terminate it or change the port range.
