### ISSUE TITLE
Crash when client terminates stream

### ISSUE THREAD

**Issue by phutchins** [Storj/storjshare-cli#75]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 4.0.0
Core:       1.1.0
Protocol:   0.7.0
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

I would expect the farmer to handle the connection closing and not crash.

### Actual Behavior

The farmer crashes.

```
{"level":"info","message":"replying to message to 8e8a5b3d9fcd57643a869d32e780d0451d873269","timestamp":"2016-06-07T18:19:22.770Z"}
{"level":"info","message":"data channel connection opened","timestamp":"2016-06-07T18:19:23.204Z"}
/opt/storj/farmer/node_modules/storj/node_modules/ws/lib/WebSocket.js:219
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (/opt/storj/farmer/node_modules/storj/node_modules/ws/lib/WebSocket.js:219:16)
    at DataChannelServer._closeSocketSuccess (/opt/storj/farmer/node_modules/storj/lib/datachannel/server.js:272:8)
    at Readable.<anonymous> (/opt/storj/farmer/node_modules/storj/lib/datachannel/server.js:239:12)
    at emitNone (events.js:67:13)
    at Readable.emit (events.js:166:7)
    at endReadableNT (/opt/storj/farmer/node_modules/storj/node_modules/readable-stream/lib/_stream_readable.js:878:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
{"level":"info","message":"you are configured to tunnel up to 10 connections","timestamp":"2016-06-07T18:19:25.831Z"}
{"level":"info","message":"node created with nodeID 02269fab17f81fcd1739f77fdb752030dde173b9","timestamp":"2016-06-07T18:19:25.861Z"}

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start streaming a file using storj cli
2. Use ctrl-c to kill the process before the streaming has started
3. Logs on one of the farmers show that it has crashed

**Comment by bookchin** [comment]
FWIW, these kind of reports should go in core. Will smash it tomorrow.
