### ISSUE TITLE
Default seeds list empty / Config wizard not working

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-cli#76]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 4.0.0
Core:       1.1.0
Protocol:   0.7.0
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

The config wizard ask me for a know seed but the default value is empty. I used the default value. I would expect one of the following 3 options.
1.) Default value is a node.
2.) Wizard refuse empty seed and ask again. That would force everyone to search for a seed.
3.) storjshare-cli is able to run with empty seed list and discover a seed.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
{"level":"info","message":"attemting to join network via ","timestamp":"2016-06-08T08:56:55.443Z"}
/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:236
    nodeID: parsed.path.substr(1)
                       ^

TypeError: Cannot read property 'substr' of null
    at FarmerInterface.Network._createContact (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:236:24)
    at FarmerInterface.Network.connect (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:222:34)
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:155:12
    at iteratee (/usr/local/lib/node_modules/storjshare-cli/node_modules/async/lib/async.js:449:17)
    at iterate (/usr/local/lib/node_modules/storjshare-cli/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/usr/local/lib/node_modules/storjshare-cli/node_modules/async/lib/async.js:281:9)
    at Object.detectSeries (/usr/local/lib/node_modules/storjshare-cli/node_modules/async/lib/async.js:462:17)
    at _trySeeds (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:153:11)
    at FarmerInterface.Network._enterOverlay (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:168:12)
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:141:10
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. storjshare setup
2. use the default seed value
3. storjshare start

**Comment by littleskunk** [comment]
Workaround for now: https://storj.readme.io/docs/storjshare-troubleshooting-guide#no-connection-to-other-nodes

**Comment by bookchin** [comment]
Ah, it must be passing an empty string to the configuration instead of nothing. Will fix.
