### ISSUE TITLE
storjshare-cli Crash

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-cli#84]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```

StorjShare: 4.0.2
Core:       1.2.1
Protocol:   0.7.0
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

Storjshare-cli crashed

[blanked]\npm\node_modules\storjshare-cli\node_modules\myspeed\node_modules\ws\lib\WebSocket.js:219
   else throw new Error('not opened');
        ^

Error: not opened
   at WebSocket.send ([blanked]\npm\node_modules\storjshare-cli\node_modules\myspeed\node_modules\ws\lib\WebSocket.js:219:16)
   at RandomStream.<anonymous> ([blanked]\npm\node_modules\storjshare-cli\node_modules\myspeed\lib\client.js:48:10)
   at emitOne (events.js:77:13)
   at RandomStream.emit (events.js:169:7)
   at readableAddChunk ([blanked]\npm\node_modules\storjshare-cli\node_modules\myspeed\node_modules\noisegen\node_modules\readable-stream\lib\_stream_readable.js:210:18)
   at RandomStream.Readable.push ([blanked]\npm\node_modules\storjshare-cli\node_modules\myspeed\node_modules\noisegen\node_modules\readable-stream\lib\_stream_readable.js:169:10)
   at InternalFieldObject.ondone ([blanked]\npm\node_modules\storjshare-cli\node_modules\myspeed\node_modules\noisegen\lib\random-stream.js:63:12)

In the debugging log it showed the following errors
{"level":"error","message":"Message signature expired","timestamp":"2016-06-13T09:22:44.497Z"}
{"type":"error","message":"Speed test ended early","timestamp":"2016-06-13T09:22:44.810Z"}

{"level":"error","message":"Could not locate renter for offer","timestamp":"2016-06-13T09:22:41.428Z"}

**Comment by bookchin** [comment]
Thanks, mind opening this issue here: https://github.com/bookchin/myspeed ?
